### ISSUE TITLE
taisei-9999 won't install

### ISSUE THREAD

**Issue by l29ah** [l29ah/booboo#33]
```
>>> Starting src_install
ninja: Entering directory `/var/tmp/paludis/games-arcade-taisei-9999/work/taisei-9999-build'
[0/1] /usr/bin/python3.5 /usr/lib/python-exec/python3.5/meson --internal install /var/tmp/paludis/games-arcade-taisei-9999/work/taisei-9999-build/meson-private/install.dat
ninja -v -j5 -l0 -C /var/tmp/paludis/games-arcade-taisei-9999/work/taisei-9999-build install
Installing src/taisei to /var/tmp/paludis/games-arcade-taisei-9999/image//usr/bin/taisei
Stripping target 'src/taisei'
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/meson", line 37, in <module>
    sys.exit(main())
  File "/usr/lib/python-exec/python3.5/meson", line 34, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib64/python3.5/site-packages/mesonbuild/mesonmain.py", line 322, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib64/python3.5/site-packages/mesonbuild/mesonmain.py", line 278, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib64/python3.5/site-packages/mesonbuild/scripts/meson_install.py", line 375, in run
    do_install(datafilename)
  File "/usr/lib64/python3.5/site-packages/mesonbuild/scripts/meson_install.py", line 190, in do_install
    install_targets(d)
  File "/usr/lib64/python3.5/site-packages/mesonbuild/scripts/meson_install.py", line 322, in install_targets
    ps, stdo, stde = Popen_safe(d.strip_bin + [outname])
  File "/usr/lib64/python3.5/site-packages/mesonbuild/mesonlib.py", line 637, in Popen_safe
    return Popen_safe_legacy(args, write=write, stderr=stderr, **kwargs)
  File "/usr/lib64/python3.5/site-packages/mesonbuild/mesonlib.py", line 648, in Popen_safe_legacy
    stderr=stderr, **kwargs)
  File "/usr/lib64/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'STRIP'
```

**Comment by Akaricchi** [comment]
Could be an incorrectly set `STRIP` env. variable? Or a meson bug; trying to execute a program named literally `STRIP` like that is suspicious. It's a shot in the dark, though.

This ebuild's dependencies are quite outdated, by the way. See here https://github.com/taisei-project/taisei#installation

**Comment by l29ah** [comment]
Wow how have you found this issue?
